// <auto-generated />
using System;
using DMFS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMFS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DMFS.Models.BreedReport", b =>
                {
                    b.Property<int>("Brid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brid"));

                    b.Property<DateTime>("BreedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CowAge")
                        .HasColumnType("int");

                    b.Property<int>("CowId")
                        .HasColumnType("int");

                    b.Property<string>("CowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCalved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeatDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PregDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Brid");

                    b.HasIndex("CowId");

                    b.ToTable("BreedReports");
                });

            modelBuilder.Entity("DMFS.Models.Cow", b =>
                {
                    b.Property<int>("CowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CowId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EarTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactiveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Pasture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightAtBirth")
                        .HasColumnType("float");

                    b.HasKey("CowId");

                    b.ToTable("Cows");
                });

            modelBuilder.Entity("DMFS.Models.CowStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CowStatuses");
                });

            modelBuilder.Entity("DMFS.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmpDob")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DMFS.Models.ExpenditureEntry", b =>
                {
                    b.Property<int>("ExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpId"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpId");

                    b.HasIndex("EmpId");

                    b.ToTable("ExpenditureEntries");
                });

            modelBuilder.Entity("DMFS.Models.HealthReport", b =>
                {
                    b.Property<int>("RepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepId"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CowId")
                        .HasColumnType("int");

                    b.Property<string>("CowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RepDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepId");

                    b.HasIndex("CowId");

                    b.ToTable("HealthReports");
                });

            modelBuilder.Entity("DMFS.Models.IncomeEntry", b =>
                {
                    b.Property<int>("IncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncId"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("IncAmt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncId");

                    b.HasIndex("EmpId");

                    b.ToTable("IncomeEntries");
                });

            modelBuilder.Entity("DMFS.Models.MilkProduction", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<double>("AmMilk")
                        .HasColumnType("float");

                    b.Property<int>("CowId")
                        .HasColumnType("int");

                    b.Property<string>("CowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateProd")
                        .HasColumnType("datetime2");

                    
                    b.Property<double>("PmMilk")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MId");

                    b.HasIndex("CowId");

                    b.ToTable("MilkProductions");
                });

            modelBuilder.Entity("DMFS.Models.MilkSale", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Uprice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SId");

                    b.HasIndex("EmpId");

                    b.ToTable("MilkSales");
                });

            modelBuilder.Entity("DMFS.Models.BreedReport", b =>
                {
                    b.HasOne("DFMS.Models.Cow", "Cow")
                        .WithMany("BreedReports")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cow");
                });

            modelBuilder.Entity("DMFS.Models.ExpenditureEntry", b =>
                {
                    b.HasOne("DFMS.Models.Employee", "Employee")
                        .WithMany("ExpenditureEntries")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DMFS.Models.HealthReport", b =>
                {
                    b.HasOne("DFMS.Models.Cow", "Cow")
                        .WithMany("HealthReports")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cow");
                });

            modelBuilder.Entity("DMFS.Models.IncomeEntry", b =>
                {
                    b.HasOne("DFMS.Models.Employee", "Employee")
                        .WithMany("IncomeEntries")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DMFS.Models.MilkProduction", b =>
                {
                    b.HasOne("DFMS.Models.Cow", "Cow")
                        .WithMany("MilkProductions")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cow");
                });

            modelBuilder.Entity("DFMS.Models.MilkSale", b =>
                {
                    b.HasOne("DFMS.Models.Employee", "Employee")
                        .WithMany("MilkSales")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DFMS.Models.Cow", b =>
                {
                    b.Navigation("BreedReports");

                    b.Navigation("HealthReports");

                    b.Navigation("MilkProductions");
                });

            modelBuilder.Entity("DFMS.Models.Employee", b =>
                {
                    b.Navigation("ExpenditureEntries");

                    b.Navigation("IncomeEntries");

                    b.Navigation("MilkSales");
                });
#pragma warning restore 612, 618
        }
    }
}
